#!/usr/bin/env bash
# ADIP one-shot bootstrap.
#
# Idempotent end-to-end pipeline:
#   1. Generate .env.local with random secrets (only if missing).
#   2. npm install (root + mini-services/analysis-ws).
#   3. Prisma generate + migrate deploy (fall back to migrate dev if no
#      migrations applied yet).
#   4. Seed admin user.
#   5. Encrypt any plaintext secrets in the DB.
#   6. Build Next.js (production standalone) and start it in the background.
#   7. Start the analysis-ws mini-service in the background.
#   8. Wait for both health endpoints, print a summary, exit 0.
#
# Logs land in ./logs/. PIDs in ./run/. Re-run is safe: existing services are
# killed before being restarted.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env.local"
LOG_DIR="$ROOT/logs"
RUN_DIR="$ROOT/run"
mkdir -p "$LOG_DIR" "$RUN_DIR"

NEXT_PORT="${NEXT_PORT:-3000}"
WS_PORT="${WS_PORT:-3003}"
NEXT_PID_FILE="$RUN_DIR/next.pid"
WS_PID_FILE="$RUN_DIR/ws.pid"

log()  { printf '\033[36m[bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[bootstrap]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 0. Sanity
# ---------------------------------------------------------------------------
command -v node >/dev/null || die "node not found on PATH."
command -v npm  >/dev/null || die "npm not found on PATH."

# Random hex secret of N bytes using node (always present).
rand_hex() { node -e "console.log(require('crypto').randomBytes($1).toString('hex'))"; }
rand_b64() { node -e "console.log(require('crypto').randomBytes($1).toString('base64'))"; }

# ---------------------------------------------------------------------------
# 1. .env.local
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  log "writing $ENV_FILE (fresh secrets)..."
  ADIP_ENCRYPTION_KEY="$(rand_hex 32)"
  ADIP_INTERNAL_TOKEN="$(rand_hex 32)"
  NEXTAUTH_SECRET="$(rand_b64 32)"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/bootstrap.sh — safe to edit by hand.

# Phase 0.1: switched from SQLite to Postgres (pgvector image).
# docker-compose.yml brings the container up on :5433 to avoid collision
# with any other Postgres the developer may run on the default port.
DATABASE_URL="postgresql://adip:adip@localhost:5433/adip?schema=public"
REDIS_URL="redis://localhost:6380"

ADIP_ENCRYPTION_KEY=$ADIP_ENCRYPTION_KEY
ADIP_INTERNAL_TOKEN=$ADIP_INTERNAL_TOKEN
ADIP_PUBLIC_ORIGIN=http://localhost:$NEXT_PORT
ADIP_WS_INTERNAL_URL=http://localhost:$WS_PORT
NEXT_PUBLIC_WS_URL=http://localhost:$WS_PORT
ADIP_WS_BIND_HOST=127.0.0.1

NEXTAUTH_SECRET=$NEXTAUTH_SECRET
NEXTAUTH_URL=http://localhost:$NEXT_PORT

ADIP_ADMIN_EMAIL=admin@local
ADIP_ADMIN_PASSWORD=admin
EOF
  chmod 600 "$ENV_FILE"
else
  log ".env.local already exists — leaving it alone."
fi

# Export every var for the rest of this script.
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

# ---------------------------------------------------------------------------
# 1.5 Docker stack (Postgres + Redis)
# ---------------------------------------------------------------------------
if command -v docker >/dev/null 2>&1; then
  log "starting docker compose stack (postgres + redis)..."
  docker compose up -d >/dev/null
  # Wait for Postgres to accept connections before running migrations.
  until docker exec adip-postgres pg_isready -U adip -d adip >/dev/null 2>&1; do
    sleep 1
  done
  # Ensure pgvector extension is present (idempotent).
  docker exec adip-postgres psql -U adip -d adip -c "CREATE EXTENSION IF NOT EXISTS vector;" >/dev/null
  log "postgres ready on :5433, redis on :6380, pgvector enabled"
else
  warn "docker not found — assuming Postgres + Redis are already reachable at DATABASE_URL / REDIS_URL"
fi

# ---------------------------------------------------------------------------
# 2. Dependencies
# ---------------------------------------------------------------------------
log "npm install (root)..."
npm install --no-fund --no-audit --loglevel=error

log "npm install (mini-services/analysis-ws)..."
( cd mini-services/analysis-ws && npm install --no-fund --no-audit --loglevel=error )

# ---------------------------------------------------------------------------
# 3. Database
# ---------------------------------------------------------------------------
mkdir -p "$ROOT/db"
log "prisma generate..."
npx prisma generate >/dev/null

log "prisma migrate deploy..."
npx prisma migrate deploy

# ---------------------------------------------------------------------------
# 4. Seed admin (idempotent)
# ---------------------------------------------------------------------------
log "seeding admin user ($ADIP_ADMIN_EMAIL)..."
npm run seed:admin --silent

# ---------------------------------------------------------------------------
# 5. Encrypt any pre-existing plaintext secrets
# ---------------------------------------------------------------------------
log "running secret migration (idempotent)..."
npm run secrets:migrate --silent

# ---------------------------------------------------------------------------
# 6. Stop anything we previously started
# ---------------------------------------------------------------------------
stop_pid() {
  local f="$1" label="$2"
  if [ -f "$f" ]; then
    local pid
    pid="$(cat "$f")"
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      log "stopping previous $label (pid=$pid)..."
      kill "$pid" 2>/dev/null || true
      sleep 1
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$f"
  fi
}
stop_pid "$NEXT_PID_FILE" "Next.js"
stop_pid "$WS_PID_FILE"   "analysis-ws"

# ---------------------------------------------------------------------------
# 7. Build Next.js
# ---------------------------------------------------------------------------
log "building Next.js (production)..."
npm run build >"$LOG_DIR/build.log" 2>&1 || {
  warn "build failed — see $LOG_DIR/build.log"
  exit 1
}

# ---------------------------------------------------------------------------
# 8. Start services
# ---------------------------------------------------------------------------
log "starting analysis-ws on :$WS_PORT..."
( cd mini-services/analysis-ws && PORT="$WS_PORT" nohup npm run start >"$LOG_DIR/ws.log" 2>&1 ) &
echo $! >"$WS_PID_FILE"

log "starting Next.js standalone on :$NEXT_PORT..."
# Run from the project root so any relative paths (Prisma adapter, etc.)
# resolve consistently. server.js path is given absolute.
nohup env PORT="$NEXT_PORT" HOSTNAME=0.0.0.0 \
  DATABASE_URL="$DATABASE_URL" \
  ADIP_ENCRYPTION_KEY="$ADIP_ENCRYPTION_KEY" \
  ADIP_INTERNAL_TOKEN="$ADIP_INTERNAL_TOKEN" \
  ADIP_WS_INTERNAL_URL="$ADIP_WS_INTERNAL_URL" \
  ADIP_PUBLIC_ORIGIN="$ADIP_PUBLIC_ORIGIN" \
  NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
  NEXTAUTH_URL="$NEXTAUTH_URL" \
  NEXT_PUBLIC_WS_URL="$NEXT_PUBLIC_WS_URL" \
  node "$ROOT/.next/standalone/server.js" >"$LOG_DIR/next.log" 2>&1 &
echo $! >"$NEXT_PID_FILE"

# ---------------------------------------------------------------------------
# 9. Wait for health
# ---------------------------------------------------------------------------
wait_for() {
  local url="$1" label="$2" max="$3"
  local i=0
  until curl -fsS -o /dev/null "$url"; do
    i=$((i + 1))
    if [ "$i" -ge "$max" ]; then
      warn "$label did not become ready after $max tries — see logs/"
      return 1
    fi
    sleep 1
  done
  log "$label up at $url"
}

# Next.js health: /api (the root API handler returns {ok:true} + kicks janitor).
# That endpoint is in the middleware's public allow-list, so no auth needed.
wait_for "http://localhost:$NEXT_PORT/api" "Next.js" 60 || exit 1
wait_for "http://localhost:$WS_PORT/healthz" "analysis-ws" 30 || exit 1

cat <<EOF

ADIP is up.

  Next.js   : http://localhost:$NEXT_PORT
  WebSocket : http://localhost:$WS_PORT  (proxy via Caddy :82 in prod)
  Sign-in   : http://localhost:$NEXT_PORT/auth/signin
              email:    $ADIP_ADMIN_EMAIL
              password: $ADIP_ADMIN_PASSWORD

Logs:    $LOG_DIR/{next,ws,build}.log
PIDs:    $RUN_DIR/{next,ws}.pid

Stop with:
  kill \$(cat $NEXT_PID_FILE $WS_PID_FILE) 2>/dev/null
EOF
